kumuluzee:
  name: ms-about
  env:
    name: dev
  version: 2.0.0
  server:
      base-url:
      http:
        port:
  config:
    etcd:
      hosts: http://localhost:52379
  discovery:
    etcd:
      hosts: http://localhost:52379
    ttl: 20
    ping-interval: 15
  cors-filter:
    servlet:
      allow-origin: "*"
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: false
      level: INFO
      period-s: 30
    checks:
      disk-space-health-check:
        threshold: 100000000
  metrics:
    generic-registry-name: default
    jvm:
      enabled: true
      registry-name: jvm
    servlet:
      enabled: true
      mapping: /metrics
    logs:
      enabled: false
      period-s: 30
      level: INFO
    web-instrumentation:
      - name: about-endpoint
        url-pattern: /api/v1/About/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="user">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="478be714-4c75-404b-b5ba-93b9a63053a0-ls.logit.io" port="16043" protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <Logger name="si.fri.rsobook.rest.AboutResource" level="trace" additivity="false">
                              <AppenderRef ref="console"/>
                              <AppenderRef ref="logstash"/>
                          </Logger>
                          <Root level="info">
                              <AppenderRef ref="console"/>
                          </Root>
                      </Loggers>
                  </Configuration>'